version: '3.8'

services:
  worker:
    build: .
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # Optional: You can override the default concurrency here if needed
    # environment:
    #   - WORKER_CONCURRENCY=5

  flower:
    build: .
    command: celery -A wqb.tasks flower --address=0.0.0.0 --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1

