version: '3.8'

services:
  # 核心模拟任务Worker，保持不变
  worker-simulations:
    build: .
    command: celery -A wqb.celery worker --loglevel=info --concurrency=3 -Q celery
    env_file:
      - .env

  # 合并后的定时任务服务
  periodic-service:
    build: .
    command: >
            celery -A wqb.celery worker --loglevel=info --concurrency=1 -Q periodic_queue -B
    env_file:
      - .env
