version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    ports:
      - "5672:5672"  # For Celery workers
      - "15672:15672" # For the RabbitMQ Management UI

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A wqb.tasks worker --loglevel=info --concurrency=8"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - rabbitmq

  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - rabbitmq
