version: '3.8'

services:
  # 核心模拟任务Worker，保持不变
  worker-simulations:
    build: .
    # command: celery -A wqb.tasks worker --loglevel=info --concurrency=3 -Q celery
    command: celery -A wqb.tasks worker --loglevel=info --concurrency=3
    env_file:
      - .env

  # 合并后的定时任务服务
  periodic-service:
    build: .
    command: >
      celery -A wqb.tasks worker --loglevel=info --concurrency=1 -Q periodic_queue -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env