version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A wqb.tasks worker --loglevel=info --concurrency=${CELERY_CONCURRENCY:-8}"
    volumes:
      - .:/app
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    env_file:
      - .env

  flower:
    image: mher/flower:0.9.7
    ports:
      - "5555:5555"
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - worker
