name: Docker Image CI

on:
  push:
    branches:
      - master

env:
  REGISTRY: docker.io
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # We need to fetch all history for proper version bumping
      with:
        fetch-depth: 0

    - name: Read current version
      id: version
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      id: build_and_push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE_NAME }}:latest
          ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
          ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Bump version
      run: |
        # Use awk to increment the patch version number
        current_version=$(cat VERSION)
        new_version=$(echo $current_version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
        echo $new_version > VERSION
        echo "New version: $new_version"

    - name: Commit and push new version
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "ci: Bump version to $(cat VERSION)"
        file_pattern: VERSION
        commit_user_name: "GitHub Actions Bot"
        commit_user_email: "actions@github.com"
        commit_author: "GitHub Actions Bot <actions@github.com>"